### PR TITLE
ci: coding style checker

### PR DESCRIPTION
**Pull request by MasterLaplace**
Add the Clang-Format configuration file and apply it via a git action.

Partially linked to:
- #13

### CODE REVIEW

**Comment by Miou-zora** [comment]
We must have the possibility to run this locally, there is a way to do it ?

**Review by Miou-zora — CHANGES_REQUESTED** [review]
We must have the possibility to run this locally, there is a way to do it ?

**Comment by MasterLaplace** [comment]
> We must have the possibility to run this locally, is there a way to do it ?

Unfortunately, there's no easy way to apply the clang format recursively from the command line.
I use the 'find' command in a Linux environment.
However, the file can be used by the IDE.

```sh
find . -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format -i
```

**Comment by Miou-zora** [comment]
> > We must have the possibility to run this locally, is there a way to do it ?
> 
> Unfortunately, there's no easy way to apply the clang format recursively from the command line. I use the 'find' command in a Linux environment. However, the file can be used by the IDE.
> 
> ```shell
> find . -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format -i
> ```

Can you find a way to use it on windows please ?

**Comment by MasterLaplace** [comment]
> > > We must have the possibility to run this locally, is there a way to do it ?
> > 
> > 
> > Unfortunately, there's no easy way to apply the clang format recursively from the command line. I use the 'find' command in a Linux environment. However, the file can be used by the IDE.
> > ```shell
> > find . -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format -i
> > ```
> 
> Can you find a way to use it on windows please ?

For powershell:
```sh
Get-ChildItem -Recurse -Include *.cpp, *.hpp | ForEach-Object {
    clang-format -i $_.FullName
}
```

**Comment by Miou-zora** [comment]
Please, fix conflicts, put theses 2 commands (for linux and for windows) with dependencies into the documentation (README is enough) and you can merge this PR

**Comment by MasterLaplace** [comment]
> Please, fix conflicts, put theses 2 commands (for linux and for windows) with dependencies into the documentation (README is enough) and you can merge this PR

Both commands are already in the README, and as for the conflicts, since it was your code, I wanted to let you take care of them.

**Review by Miou-zora — APPROVED** [review]

**Pull request merged**
